particle1:
  n: 20
  mass: 1.0
  charge: -1.0
  spin: 1
  radius: 1
  color: 'blue'
  n_trail_points: 10

particle2:
  n: 20
  mass: 1.0
  charge: 1.0
  spin: 1
  radius: 1
  color: 'red'
  n_trail_points: 10

particle3:
  n: 20
  mass: 10
  charge: 1.0
  spin: 1
  radius: 1
  color: 'green'
  n_trail_points: 10

particle4:
  n: 20
  mass: 1.0
  charge: -1.0
  spin: 1
  radius: 1
  color: 'yellow'
  n_trail_points: 10

particle5:
  n: 20
  mass: 1.0
  charge: -1.0
  spin: 1
  radius: 1
  color: 'pink'
  n_trail_points: 10

boundary:
  box_size: 1000
  type: 'reflective'

