simulation:
  #Simulation properties
  name: 'simulation6'
  dt: .5
  animate_every: 5
  frames: 1000
  interval: 20
  fps: 30
  bitrate: 1800
  store_values: False
  show_trails: True
  n_trail_points: 30
  use_cpu: true
  #mode: ['simulate','save'] #available modes: 'run', 'simulate', 'save'
  mode: 'save'
  #mode: 'run'
  compare: False

physics:
  #Set forces to be about equal in strength
  G: 100
  K: 1e-12
  c: 1
  e_0: 1
  mu_0: 1
  hbar: 1

boundary:
  box_size: 1000
  type: 'reflective'

grid:
  divisions: 0