simulation:
  #Simulation properties
  name: 'simulation'
  dt: 0.1
  animate_every: 10
  frames: 30
  interval: 20
  fps: 10
  bitrate: 1800
  store_values: False
  show_trails: True
  n_trail_points: 300
  #mode: ['simulate','save'] #available modes: 'run', 'simulate', 'save'
  mode: 'save'
  #mode: 'run'
  compare: True
  use_fields: False

physics:
  #Set forces to be about equal in strength
  G: 10000000
  K: 1e-12
  c: 3e8
  e_0: 1
  mu_0: 1
  hbar: 1

boundary:
  box_size: 1000
  type: 'reflective'

fields:
  divisions: 2
  show_field: 
  gravity:
    dynamic: True #update field every frame
    type: 'gravity'

